### ISSUE TITLE
bower resolutions problem

### ISSUE THREAD

**Issue by ayr-ton** [mining/frontend#1]
For avoid dependencies conflict, add a "resolutions" section at bower.json, after "dependencies" section like this for avoid resolutions interactive challenge when installing bower dependencies:

```
"resolutions": {                                                                   
    "angular": "1.3.11",                                                             
    "select2": "~3.5.2"                                                              
}
```

I chose the last stable angular release, but you can keep the 1.2.28 version. If you also chose to upgrade, ping me for help in fix the post update bugs.

**Comment by lerrua** [comment]
@ayr-ton I'm trying apply your fix adding a "resolutions" hash using angular 1.3.11 but I'm having this following error at dashboard:

```
[Error] Error: [$injector:modulerr] Failed to instantiate module miningApp due to:
[$injector:modulerr] Failed to instantiate module miningApp.auth due to:
undefined is not an object (evaluating '$httpProvider.responseInterceptors.push')
http://localhost:8888/assets/app/scripts/auth/auth.js:45:39
```

![screen shot 2015-06-24 at 12 00 37 pm](https://cloud.githubusercontent.com/assets/154603/8333368/ed4bc8f8-1a68-11e5-8149-5d64a0861396.png)

I'm googling it and i found this answer http://stackoverflow.com/a/21269115

Anyway, can you help me?

**Comment by lerrua** [comment]
@avelino @ayr-ton 
my last PR and this commit ab8db0992bac7f0b8ff4f8ec2a64f1178d40c775 will fix this issue. ;)
